/*
 *	Tide Editor
 *	buildinfo.cc
 *
 *	Copyright (C) 2012-2013 Tom Samstag
 *	Based on HT Editor
 *
 *	This program is free software; you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License version 2 as
 *	published by the Free Software Foundation.
 *
 *	This program is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with this program; if not, write to the Free Software
 *	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include "copyrightinfo.h"
#include <string.h>

#define ht_author1 "Stefan Weyergraf"
#define ht_copyright1 "(c) 1999-2004 "ht_author1

#define ht_author2 "Sebastian Biallas"
#define ht_mail2 "sb@biallas.net"
#define ht_copyright2 "(c) 1999-2013 "ht_author2" <"ht_mail2">"

const char *copyright_text[]=
{
	program_name" "program_version" (%s) "__TIME__" on "__DATE__,
	ht_copyright1,
	ht_copyright2,
	NULL
};

const char *copyright_html[]=
{
	"generated by <a href=\""program_url"\">"program_name" version "program_version"</a>.",
	NULL
};


